api_keys:
  calendarific: "your_calendarific_api_key"
  openweathermap: "your_openweathermap_api_key"
  googlemaps: "your_google_maps_api_key"
settings:
  country: "NG"
  weather_location: "Lagos,NG"
  start_date: "2023-01-01"
  end_date: "2023-12-31"
